name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      # Use the latest checkout version
      - name: Checkout code
        uses: actions/checkout@v4

      # Use the latest setup-node version and ensure Node.js 20 is used
      - name: Set up Node.js
        uses: actions/setup-node@v4

      # Install dependencies
      - name: Clean install dependencies and build
        run: |
          npm ci
          npm run build


      # Run tests
      - name: Run tests
        run: npm test

      # Generate build artifacts
      - name: Build application
        run: npm run build

      # Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    env:
      # Force GitHub Actions to use Node.js 20 runtime for deployment as well
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      # Checkout the code again
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./build s3://cool_bucket --delete --region us-east-2




