name: CI Workflow

# Trigger the workflow on every push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java, Node.js, or the environment required for your project
      - name: Set up Node.js (if using Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Adjust to your version
      
      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

      # Generate build artifacts
      - name: Build application
        run: npm run build

      # Upload build artifacts (optional)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

